name: basic
on:
  push:
    branches: ['master']
jobs:
  prob19tests:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: wenkokke/setup-agda@v2
        with:
          agda-version: '2.6.2.2'
          agda-stdlib-version: 'recommended'
          agda-defaults: |
            standard-library

      - run: |
          agda -c AVL.agda --no-main
        working-directory: .