name: basic
on:
  push:
    branches: ['master']
jobs:
  prob19tests:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: wenkokke/setup-agda@v2
        with:
          agda-version: '2.7.0.1'
          agda-stdlib-version: '2.1.1'

      - run: |
          agda -c AVL.agda --no-main
        working-directory: .