name: basic
on:
  push:
    branches: ['master']

env:
  PROJECT_DIR : lib
  SUBDIRECTORIES : AVL


jobs:
  prob19tests:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: wenkokke/setup-agda@v2
        with:
          agda-version: '2.6.4.3'
          agda-stdlib-version: '2.0'

      - run: |
          agda --compile-dir=./ --ghc-strict -c AVL/Height.agda --no-main
        working-directory: lib