name: basic
on:
  push:
    branches: ['master']
jobs:
  prob19tests:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: wenkokke/setup-agda@v2

      - run: |
          agda -c AVL.agda --no-main
        working-directory: .